# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

magick_attr_delay <- function(input, delay) {
    .Call('magick_magick_attr_delay', PACKAGE = 'magick', input, delay)
}

magick_image_verbose <- function(input) {
    .Call('magick_magick_image_verbose', PACKAGE = 'magick', input)
}

magick_image_info <- function(input) {
    .Call('magick_magick_image_info', PACKAGE = 'magick', input)
}

magick_image_length <- function(image) {
    .Call('magick_magick_image_length', PACKAGE = 'magick', image)
}

create <- function(len) {
    .Call('magick_create', PACKAGE = 'magick', len)
}

copy <- function(image) {
    .Call('magick_copy', PACKAGE = 'magick', image)
}

magick_image_rev <- function(input) {
    .Call('magick_magick_image_rev', PACKAGE = 'magick', input)
}

magick_image_join <- function(input) {
    .Call('magick_magick_image_join', PACKAGE = 'magick', input)
}

magick_image_subset <- function(image, index) {
    .Call('magick_magick_image_subset', PACKAGE = 'magick', image, index)
}

magick_coder_info <- function(format) {
    .Call('magick_magick_coder_info', PACKAGE = 'magick', format)
}

magick_frame_read <- function(x) {
    .Call('magick_magick_frame_read', PACKAGE = 'magick', x)
}

magick_frame_write <- function(frame, format) {
    .Call('magick_magick_frame_write', PACKAGE = 'magick', frame, format)
}

magick_frame_info <- function(frame) {
    .Call('magick_magick_frame_info', PACKAGE = 'magick', frame)
}

magick_image_noise <- function(input, noisetype) {
    .Call('magick_magick_image_noise', PACKAGE = 'magick', input, noisetype)
}

magick_image_blur <- function(input, radius = 1, sigma = 0.5) {
    .Call('magick_magick_image_blur', PACKAGE = 'magick', input, radius, sigma)
}

magick_image_charcoal <- function(input, radius = 1, sigma = 0.5) {
    .Call('magick_magick_image_charcoal', PACKAGE = 'magick', input, radius, sigma)
}

magick_image_chop <- function(input, geometry) {
    .Call('magick_magick_image_chop', PACKAGE = 'magick', input, geometry)
}

magick_image_colorize <- function(input, opacity, color) {
    .Call('magick_magick_image_colorize', PACKAGE = 'magick', input, opacity, color)
}

magick_image_edge <- function(input, radius) {
    .Call('magick_magick_image_edge', PACKAGE = 'magick', input, radius)
}

magick_image_emboss <- function(input, radius = 1, sigma = 0.5) {
    .Call('magick_magick_image_emboss', PACKAGE = 'magick', input, radius, sigma)
}

magick_image_enhance <- function(input) {
    .Call('magick_magick_image_enhance', PACKAGE = 'magick', input)
}

magick_image_equalize <- function(input) {
    .Call('magick_magick_image_equalize', PACKAGE = 'magick', input)
}

magick_image_flip <- function(input) {
    .Call('magick_magick_image_flip', PACKAGE = 'magick', input)
}

magick_image_flop <- function(input) {
    .Call('magick_magick_image_flop', PACKAGE = 'magick', input)
}

magick_image_fill <- function(input, color, point, fuzz) {
    .Call('magick_magick_image_fill', PACKAGE = 'magick', input, color, point, fuzz)
}

magick_image_frame <- function(input, geometry) {
    .Call('magick_magick_image_frame', PACKAGE = 'magick', input, geometry)
}

magick_image_negate <- function(input) {
    .Call('magick_magick_image_negate', PACKAGE = 'magick', input)
}

magick_image_normalize <- function(input) {
    .Call('magick_magick_image_normalize', PACKAGE = 'magick', input)
}

magick_image_oilpaint <- function(input, radius) {
    .Call('magick_magick_image_oilpaint', PACKAGE = 'magick', input, radius)
}

magick_image_rotate <- function(input, degrees) {
    .Call('magick_magick_image_rotate', PACKAGE = 'magick', input, degrees)
}

magick_image_implode <- function(input, factor) {
    .Call('magick_magick_image_implode', PACKAGE = 'magick', input, factor)
}

magick_image_format <- function(input, format) {
    .Call('magick_magick_image_format', PACKAGE = 'magick', input, format)
}

magick_image_trim <- function(input) {
    .Call('magick_magick_image_trim', PACKAGE = 'magick', input)
}

magick_image_composite <- function(input, composite_image, offset, op) {
    .Call('magick_magick_image_composite', PACKAGE = 'magick', input, composite_image, offset, op)
}

magick_image_contrast <- function(input, sharpen) {
    .Call('magick_magick_image_contrast', PACKAGE = 'magick', input, sharpen)
}

magick_image_background <- function(input, color) {
    .Call('magick_magick_image_background', PACKAGE = 'magick', input, color)
}

magick_image_crop <- function(input, geometry) {
    .Call('magick_magick_image_crop', PACKAGE = 'magick', input, geometry)
}

magick_image_scale <- function(input, geometry) {
    .Call('magick_magick_image_scale', PACKAGE = 'magick', input, geometry)
}

magick_image_sample <- function(input, geometry) {
    .Call('magick_magick_image_sample', PACKAGE = 'magick', input, geometry)
}

magick_image_border <- function(input, color, geometry) {
    .Call('magick_magick_image_border', PACKAGE = 'magick', input, color, geometry)
}

magick_image_annotate <- function(input, text, location) {
    .Call('magick_magick_image_annotate', PACKAGE = 'magick', input, text, location)
}

magick_image_read <- function(x) {
    .Call('magick_magick_image_read', PACKAGE = 'magick', x)
}

magick_image_read_list <- function(list) {
    .Call('magick_magick_image_read_list', PACKAGE = 'magick', list)
}

magick_image_write <- function(image) {
    .Call('magick_magick_image_write', PACKAGE = 'magick', image)
}

magick_image_display <- function(image) {
    .Call('magick_magick_image_display', PACKAGE = 'magick', image)
}

magick_image_animate <- function(image) {
    .Call('magick_magick_image_animate', PACKAGE = 'magick', image)
}

magick_image_append <- function(image, stack) {
    .Call('magick_magick_image_append', PACKAGE = 'magick', image, stack)
}

magick_image_average <- function(image) {
    .Call('magick_magick_image_average', PACKAGE = 'magick', image)
}

magick_image_coalesce <- function(image) {
    .Call('magick_magick_image_coalesce', PACKAGE = 'magick', image)
}

magick_image_flatten <- function(image) {
    .Call('magick_magick_image_flatten', PACKAGE = 'magick', image)
}

magick_image_fft <- function(image) {
    .Call('magick_magick_image_fft', PACKAGE = 'magick', image)
}

magick_image_map <- function(input, map_image, dither) {
    .Call('magick_magick_image_map', PACKAGE = 'magick', input, map_image, dither)
}

magick_image_montage <- function(image) {
    .Call('magick_magick_image_montage', PACKAGE = 'magick', image)
}

magick_image_morph <- function(image, frames) {
    .Call('magick_magick_image_morph', PACKAGE = 'magick', image, frames)
}

magick_image_mosaic <- function(image) {
    .Call('magick_magick_image_mosaic', PACKAGE = 'magick', image)
}

