# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

animate <- function(list, format, animationDelay = 100L) {
    .Call('magick_animate', PACKAGE = 'magick', list, format, animationDelay)
}

convert_to <- function(x, format) {
    .Call('magick_convert_to', PACKAGE = 'magick', x, format)
}

magick_coder_info <- function(format) {
    .Call('magick_magick_coder_info', PACKAGE = 'magick', format)
}

