on:
  push:
  pull_request:

name: RHUB-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    name: r-hub2/${{ matrix.container }} ${{ matrix.legacyjpeg && 'legacy-jpeg' || 'turbojpeg' }}
    container: ghcr.io/r-hub/containers/${{ matrix.container }}:latest
    strategy:
      fail-fast: false
      matrix:
        container: [ 'clang18', 'clang20', 'ubuntu-clang' ]
        legacyjpeg: [ true, false ]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install legacy libjpeg
        if: matrix.legacyjpeg
        run: apt-get install -y libjpeg62
        shell: bash

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
